# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import annuaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualitesAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_artl', models.CharField(choices=[('1', 'Actualites'), ('2', "Appels d'Offres")], max_length=2, verbose_name='Types de la publication *', help_text='Types de la publication *')),
                ('titre_artl', models.CharField(verbose_name='Titre de la publication *', max_length=100, help_text='Titre de la publication *')),
                ('description_artl', models.TextField(verbose_name='Description de la publication *', max_length=500, help_text='Description de la publication *')),
                ('image_artl', models.ImageField(upload_to=annuaire.models.ActualitesAO.user_directory_path, help_text='Image de la publication')),
                ('lien_artl', models.URLField(verbose_name='Lien pour la publication *', help_text='Lien pour la publication *')),
            ],
        ),
        migrations.CreateModel(
            name='AuthLDAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True, max_length=255, verbose_name='utilisateur')),
                ('ldap_hash', models.CharField(max_length=255, verbose_name='hash LDAP')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('f', 'Francais'), ('e', 'Espagnol')], max_length=1)),
                ('etablissement', models.CharField(verbose_name='Université', blank=True, max_length=255, null=True)),
                ('etablissement_autre_nom', models.CharField(verbose_name='faculté/institut/école', blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('m', 'Homme'), ('f', 'Femme')], max_length=1)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=128, verbose_name='prénom')),
                ('courriel', models.EmailField(max_length=128, verbose_name='courriel')),
                ('afficher_courriel', models.BooleanField(default=True)),
                ('site', models.URLField(verbose_name='Site Internet', blank=True, null=True)),
                ('telephone', models.CharField(verbose_name='numéro de téléphone', blank=True, max_length=32, null=True)),
                ('telecopie', models.CharField(verbose_name='numéro de télécopie', blank=True, max_length=32, null=True)),
                ('axe', models.CharField(choices=[('1', 'Ressources vivantes naturelles'), ('2', 'Santé humaine et épidémiologie'), ('3', 'Territoires, sciences humaines, cultures et société'), ('4', 'Economie et développement'), ('5', 'Connaissance,exploitation et gestion du milieu physique')], max_length=1, verbose_name='Axe de recherche')),
                ('mots_cles', models.TextField(verbose_name='mots-clés', blank=True, max_length=255, null=True)),
                ('diplome', models.CharField(verbose_name='diplôme le plus élevé', blank=True, max_length=255, null=True)),
                ('discipline', models.TextField(blank=True, verbose_name='Enseignements dispensés')),
                ('theme_recherche', models.TextField(blank=True, verbose_name='Problématique et description de la recherche')),
                ('equipement', models.TextField(blank=True, verbose_name='Equipement disponible')),
                ('laboratoire', models.TextField(blank=True, verbose_name='Laboratoire')),
                ('terrain', models.TextField(blank=True, verbose_name='Terrain')),
                ('valorisation', models.TextField(blank=True, verbose_name='Valorisation et domaine de compétence')),
                ('partenaires', models.CharField(blank=True, max_length=255, verbose_name='Partenaires')),
                ('doctorants', models.CharField(blank=True, max_length=255)),
                ('stagiaire', models.CharField(blank=True, max_length=255, verbose_name='Autres stagiaires')),
                ('publicationsInternational', models.IntegerField(blank=True, default=0, verbose_name='Nombre de publication de niveau internationales')),
                ('publicationsAutre', models.IntegerField(blank=True, default=0, verbose_name='Autres publications')),
                ('publicationsColloc', models.IntegerField(blank=True, default=0, verbose_name="Nombre de publication ayant fait l'objet de publication dans actes de colloque")),
                ('communication', models.IntegerField(blank=True, default=0, verbose_name='Autres communications')),
                ('equipe', models.BooleanField(verbose_name='Etes-vous intéressé à créer ou intégrer une équipe de recherche?')),
                ('domaine', models.CharField(blank=True, max_length=255, verbose_name='Si oui dans quel domaine?')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='date de creation')),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom', 'prenom', 'langue'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('f', 'Francais'), ('e', 'Espagnol')], max_length=1)),
                ('etablissement', models.CharField(verbose_name='Université', blank=True, max_length=255, null=True)),
                ('etablissement_autre_nom', models.CharField(verbose_name='Faculté/institut/école', blank=True, max_length=255, null=True)),
                ('intitule', models.CharField(max_length=255, verbose_name="Intitulé de l'équipe de recherche")),
                ('axe', models.CharField(choices=[('1', 'Ressources vivantes naturelles'), ('2', 'Santé humaine et épidémiologie'), ('3', 'Territoires, sciences humaines, cultures et société'), ('4', 'Economie et développement'), ('5', 'Connaissance,exploitation et gestion du milieu physique')], max_length=1)),
                ('date_creation', models.DateField(blank=True, verbose_name='Date de creation', null=True)),
                ('date_evaluation', models.DateField(blank=True, verbose_name='Date de la dernière évaluation', null=True)),
                ('genre', models.CharField(choices=[('m', 'Homme'), ('f', 'Femme')], max_length=1)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du responsable')),
                ('prenom', models.CharField(max_length=128, verbose_name='Prénom du responsable')),
                ('courriel', models.EmailField(max_length=128, verbose_name='courriel')),
                ('afficher_courriel', models.BooleanField(default=True, verbose_name='Afficher le courriel')),
                ('site', models.URLField(verbose_name='Site Internet', blank=True, null=True)),
                ('telephone', models.CharField(verbose_name='Numéro de téléphone', blank=True, max_length=32, null=True)),
                ('telecopie', models.CharField(verbose_name='Numéro de télécopie', blank=True, max_length=32, null=True)),
                ('prof', models.IntegerField(blank=True, default=0, verbose_name='Nombre de professeurs')),
                ('maitre', models.IntegerField(blank=True, default=0, verbose_name='Nombre de maîtres de conférence')),
                ('assistant', models.IntegerField(blank=True, default=0, verbose_name="Nombre d'assistants")),
                ('chercheur', models.IntegerField(blank=True, default=0, verbose_name='Nombre de chercheurs')),
                ('autres', models.IntegerField(blank=True, default=0, verbose_name='Autres')),
                ('presentation', models.TextField(blank=True, verbose_name='Présentation')),
                ('problematique', models.TextField(blank=True, verbose_name='Problématique et description succinte de la recherche')),
                ('mots_cles', models.TextField(blank=True, verbose_name='mots-clés', null=True)),
                ('equipement', models.TextField(blank=True, verbose_name='Equipement disponible')),
                ('laboratoire', models.TextField(blank=True, verbose_name='Laboratoire')),
                ('terrain', models.TextField(blank=True, verbose_name='Terrain')),
                ('valorisation', models.TextField(blank=True, verbose_name='Valorisation et domaine de compétence')),
                ('partenaires', models.TextField(blank=True, verbose_name='Partenaires')),
                ('enseignant', models.TextField(blank=True, verbose_name="Liste des enseignants-chercheurs de l'unité")),
                ('doctorants', models.IntegerField(blank=True, default=0)),
                ('stagiaire', models.IntegerField(blank=True, default=0, verbose_name='Autres stagiaires')),
                ('publicationsInternational', models.IntegerField(blank=True, default=0, verbose_name='Nombre de publication de niveau internationales')),
                ('publicationsAutre', models.IntegerField(blank=True, default=0, verbose_name='Autres publications')),
                ('publicationsColloc', models.IntegerField(blank=True, default=0, verbose_name="Nombre de publication ayant fait l'objet de publication dans actes de colloque")),
                ('communication', models.IntegerField(blank=True, default=0, verbose_name='Autres communications')),
                ('complement', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='date de publication')),
                ('actif', models.BooleanField(default=False)),
                ('etablissement_autre_pays', models.ForeignKey(db_column='etablissement_autre_pays', to='references.Pays', related_name='etablissement_autre_pays_equipe', blank=True, null=True, to_field='code', verbose_name="Pays de l'établissement")),
            ],
            options={
                'ordering': ['nom', 'prenom', 'langue'],
            },
        ),
        migrations.CreateModel(
            name='PublicationsMajeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteurs', models.CharField(blank=True, max_length=255, verbose_name='auteur(s)')),
                ('titre', models.CharField(verbose_name='titre', blank=True, max_length=255, null=True)),
                ('revue', models.CharField(verbose_name='revue', blank=True, max_length=255, null=True)),
                ('annee', models.CharField(verbose_name='Date de publication', blank=True, max_length=255, null=True)),
                ('nb_pages', models.CharField(verbose_name='nombre de pages', blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsMajeurEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteurs', models.CharField(blank=True, max_length=255, verbose_name='auteur(s)')),
                ('titre', models.CharField(verbose_name='titre', blank=True, max_length=255, null=True)),
                ('revue', models.CharField(verbose_name='revue', blank=True, max_length=255, null=True)),
                ('annee', models.CharField(verbose_name='Date de publication', blank=True, max_length=255, null=True)),
                ('nb_pages', models.CharField(verbose_name='nombre de pages', blank=True, max_length=255, null=True)),
                ('chercheur', models.ForeignKey(related_name='publications', to='annuaire.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('chercheur', models.OneToOneField(primary_key=True, serialize=False, to='annuaire.Chercheur')),
                ('titre', models.CharField(verbose_name='Titre', blank=True, max_length=255, null=True)),
                ('annee', models.IntegerField(blank=True, verbose_name='Année de soutenance (réalisée ou prévue)', null=True)),
                ('directeur', models.CharField(verbose_name='Directeur', blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(verbose_name='Établissement de soutenance', blank=True, max_length=255, null=True)),
                ('nb_pages', models.IntegerField(blank=True, verbose_name='Nombre de pages', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicationsmajeur',
            name='chercheur',
            field=models.ForeignKey(related_name='publications', to='annuaire.Chercheur'),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='etablissement_autre_pays',
            field=models.ForeignKey(db_column='etablissement_autre_pays', to='references.Pays', related_name='etablissement_autre_pays', blank=True, null=True, to_field='code', verbose_name="pays de l'établissement"),
        ),
    ]
