# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import annuaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualitesAO',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('type_artl', models.CharField(help_text='Types de la publication *', max_length=2, verbose_name='Types de la publication *', choices=[('1', 'Actualites'), ('2', "Appels d'Offres")])),
                ('titre_artl', models.CharField(help_text='Titre de la publication *', max_length=100, verbose_name='Titre de la publication *')),
                ('description_artl', models.TextField(help_text='Description de la publication *', max_length=500, verbose_name='Description de la publication *')),
                ('image_artl', models.ImageField(help_text='Image de la publication', upload_to=annuaire.models.ActualitesAO.user_directory_path)),
                ('lien_artl', models.URLField(help_text='Lien pour la publication *', verbose_name='Lien pour la publication *')),
            ],
        ),
        migrations.CreateModel(
            name='AuthLDAP',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='utilisateur')),
                ('ldap_hash', models.CharField(max_length=255, verbose_name='hash LDAP')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('langue', models.CharField(max_length=1, choices=[('f', 'Francais'), ('e', 'Espagnol')])),
                ('etablissement', models.CharField(max_length=255, null=True, blank=True, verbose_name='Université')),
                ('etablissement_autre_nom', models.CharField(max_length=255, null=True, blank=True, verbose_name='faculté/institut/école')),
                ('genre', models.CharField(max_length=1, choices=[('m', 'Homme'), ('f', 'Femme')])),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=128, verbose_name='prénom')),
                ('courriel', models.EmailField(max_length=128, verbose_name='courriel')),
                ('afficher_courriel', models.BooleanField(default=True)),
                ('site', models.URLField(null=True, blank=True, verbose_name='Site Internet')),
                ('telephone', models.CharField(max_length=32, null=True, blank=True, verbose_name='numéro de téléphone')),
                ('telecopie', models.CharField(max_length=32, null=True, blank=True, verbose_name='numéro de télécopie')),
                ('axe', models.CharField(max_length=1, verbose_name='Axe de recherche', choices=[('1', 'Ressources vivantes naturelles'), ('2', 'Santé humaine et épidémiologie'), ('3', 'Territoires, sciences humaines, cultures et société'), ('4', 'Economie et développement'), ('5', 'Connaissance,exploitation et gestion du milieu physique')])),
                ('mots_cles', models.TextField(max_length=255, null=True, blank=True, verbose_name='mots-clés')),
                ('diplome', models.CharField(max_length=255, null=True, blank=True, verbose_name='diplôme le plus élevé')),
                ('discipline', models.TextField(blank=True, verbose_name='Enseignements dispensés')),
                ('theme_recherche', models.TextField(blank=True, verbose_name='Problématique et description de la recherche')),
                ('equipement', models.TextField(blank=True, verbose_name='Equipement disponible')),
                ('laboratoire', models.TextField(blank=True, verbose_name='Laboratoire')),
                ('terrain', models.TextField(blank=True, verbose_name='Terrain')),
                ('valorisation', models.TextField(blank=True, verbose_name='Valorisation et domaine de compétence')),
                ('partenaires', models.CharField(max_length=255, blank=True, verbose_name='Partenaires')),
                ('doctorants', models.CharField(max_length=255, blank=True)),
                ('stagiaire', models.CharField(max_length=255, blank=True, verbose_name='Autres stagiaires')),
                ('publicationsInternational', models.IntegerField(default=0, blank=True, verbose_name='Nombre de publication de niveau internationales')),
                ('publicationsAutre', models.IntegerField(default=0, blank=True, verbose_name='Autres publications')),
                ('publicationsColloc', models.IntegerField(default=0, blank=True, verbose_name="Nombre de publication ayant fait l'objet de publication dans actes de colloque")),
                ('communication', models.IntegerField(default=0, blank=True, verbose_name='Autres communications')),
                ('equipe', models.BooleanField(verbose_name='Etes-vous intéressé à créer ou intégrer une équipe de recherche?')),
                ('domaine', models.CharField(max_length=255, blank=True, verbose_name='Si oui dans quel domaine?')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_pub', models.DateField(verbose_name='date de creation', auto_now_add=True)),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom', 'prenom', 'langue'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('langue', models.CharField(max_length=1, choices=[('f', 'Francais'), ('e', 'Espagnol')])),
                ('etablissement', models.CharField(max_length=255, null=True, blank=True, verbose_name='Université')),
                ('etablissement_autre_nom', models.CharField(max_length=255, null=True, blank=True, verbose_name='Faculté/institut/école')),
                ('intitule', models.CharField(max_length=255, verbose_name="Intitulé de l'équipe de recherche")),
                ('axe', models.CharField(max_length=1, choices=[('1', 'Ressources vivantes naturelles'), ('2', 'Santé humaine et épidémiologie'), ('3', 'Territoires, sciences humaines, cultures et société'), ('4', 'Economie et développement'), ('5', 'Connaissance,exploitation et gestion du milieu physique')])),
                ('date_creation', models.DateField(null=True, blank=True, verbose_name='Date de creation')),
                ('date_evaluation', models.DateField(null=True, blank=True, verbose_name='Date de la dernière évaluation')),
                ('genre', models.CharField(max_length=1, choices=[('m', 'Homme'), ('f', 'Femme')])),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du responsable')),
                ('prenom', models.CharField(max_length=128, verbose_name='Prénom du responsable')),
                ('courriel', models.EmailField(max_length=128, verbose_name='courriel')),
                ('afficher_courriel', models.BooleanField(default=True, verbose_name='Afficher le courriel')),
                ('site', models.URLField(null=True, blank=True, verbose_name='Site Internet')),
                ('telephone', models.CharField(max_length=32, null=True, blank=True, verbose_name='Numéro de téléphone')),
                ('telecopie', models.CharField(max_length=32, null=True, blank=True, verbose_name='Numéro de télécopie')),
                ('prof', models.IntegerField(default=0, blank=True, verbose_name='Nombre de professeurs')),
                ('maitre', models.IntegerField(default=0, blank=True, verbose_name='Nombre de maîtres de conférence')),
                ('assistant', models.IntegerField(default=0, blank=True, verbose_name="Nombre d'assistants")),
                ('chercheur', models.IntegerField(default=0, blank=True, verbose_name='Nombre de chercheurs')),
                ('autres', models.IntegerField(default=0, blank=True, verbose_name='Autres')),
                ('presentation', models.TextField(blank=True, verbose_name='Présentation')),
                ('problematique', models.TextField(blank=True, verbose_name='Problématique et description succinte de la recherche')),
                ('mots_cles', models.TextField(null=True, blank=True, verbose_name='mots-clés')),
                ('equipement', models.TextField(blank=True, verbose_name='Equipement disponible')),
                ('laboratoire', models.TextField(blank=True, verbose_name='Laboratoire')),
                ('terrain', models.TextField(blank=True, verbose_name='Terrain')),
                ('valorisation', models.TextField(blank=True, verbose_name='Valorisation et domaine de compétence')),
                ('partenaires', models.TextField(blank=True, verbose_name='Partenaires')),
                ('enseignant', models.TextField(blank=True, verbose_name="Liste des enseignants-chercheurs de l'unité")),
                ('doctorants', models.IntegerField(default=0, blank=True)),
                ('stagiaire', models.IntegerField(default=0, blank=True, verbose_name='Autres stagiaires')),
                ('publicationsInternational', models.IntegerField(default=0, blank=True, verbose_name='Nombre de publication de niveau internationales')),
                ('publicationsAutre', models.IntegerField(default=0, blank=True, verbose_name='Autres publications')),
                ('publicationsColloc', models.IntegerField(default=0, blank=True, verbose_name="Nombre de publication ayant fait l'objet de publication dans actes de colloque")),
                ('communication', models.IntegerField(default=0, blank=True, verbose_name='Autres communications')),
                ('complement', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_pub', models.DateField(verbose_name='date de publication', auto_now_add=True)),
                ('actif', models.BooleanField(default=False)),
                ('etablissement_autre_pays', models.ForeignKey(db_column='etablissement_autre_pays', verbose_name="Pays de l'établissement", related_name='etablissement_autre_pays_equipe', to_field='code', null=True, blank=True, to='references.Pays')),
            ],
            options={
                'ordering': ['nom', 'prenom', 'langue'],
            },
        ),
        migrations.CreateModel(
            name='LaboEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('sigle', models.CharField(help_text='Sigle du laboratoire', max_length=50, verbose_name='Sigle du laboratoire')),
                ('universite', models.CharField(help_text="Nom de l'universite d'appartenance *", max_length=100, verbose_name="Nom de l'universite d'appartenance *")),
                ('faculte', models.CharField(help_text='Faculte/Institut/Ecole *', max_length=100, verbose_name='Faculte/Institut/Ecole')),
                ('disciplinePrinci', models.CharField(help_text='Discipline Principle *', max_length=100, verbose_name='Discipline Principle *')),
                ('disciplineSecond', models.CharField(help_text='Discipline Secondaire', max_length=100, verbose_name='Discipline Secondaire')),
                ('languePrincip', models.CharField(help_text='Langue principale de travail *', max_length=5, verbose_name='Langue principale de travail *', choices=[('FR', 'Francais'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('CR', 'Creole'), ('NOP', "Pas d'autres")])),
                ('autrelangue', models.CharField(help_text='Autres langues (de facon significative > 25%) *', max_length=5, verbose_name='Autres langues (de facon significative > 25%) *', choices=[('FR', 'Francais'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('CR', 'Creole'), ('NOP', "Pas d'autres")])),
                ('anneeCreation', models.CharField(help_text='Annee de creation(AAAA) *', max_length=5, verbose_name='Annee de creation(AAAA) *')),
                ('anneeLastEval', models.CharField(help_text="Annee de la derniere evaluation (AAAA)* <i>inscrire 0000 si le laboratoire n'a jamais ete evalue</i>", max_length=5, verbose_name="Annee de la derniere evaluation (AAAA)* <i>inscrire 0000 si le laboratoire n'a jamais ete evalue</i>")),
                ('adresse', models.CharField(help_text='Adresse *', max_length=100, verbose_name='Adresse *')),
                ('ville', models.CharField(help_text='Ville *', max_length=100, verbose_name='Ville *')),
                ('telNum', models.CharField(help_text='Numero de telephone *', max_length=20, verbose_name='Numero de telephone *')),
                ('email', models.EmailField(help_text='Adresse mail generale *', max_length=100, verbose_name='Adresse mail generale *')),
                ('siteInternet', models.URLField(help_text='Site internet', verbose_name='Site internet')),
                ('pays', models.CharField(help_text='Pays *', max_length=100, verbose_name='Pays *', choices=[('Afghanistan', 'Afghanistan'), ('Afrique du Sud', 'Afrique du Sud'), ('Albanie', 'Albanie'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Andorre', 'Andorre'), ('Angola', 'Angola'), ('Antigua-Et-Barbuda', 'Antigua-Et-Barbuda'), ('Arabie Saoudite', 'Arabie Saoudite'), ('Argentine', 'Argentine'), ('Arménie', 'Arménie'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Azerbaïdjan', 'Azerbaïdjan'), ('Bahamas', 'Bahamas'), ('Bahreïn', 'Bahreïn'), ('Bangladesh', 'Bangladesh'), ('Barbade', 'Barbade'), ('Bélarus', 'Bélarus'), ('Belgique', 'Belgique'), ('Belize', 'Belize'), ('Bénin', 'Bénin'), ('Bhoutan', 'Bhoutan'), ('Bolivie', 'Bolivie'), ('Bosnie-Herzégovine', 'Bosnie-Herzégovine'), ('Botswana', 'Botswana'), ('Brésil', 'Brésil'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgarie', 'Bulgarie'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodge'), ('Cameroun', 'Cameroun'), ('Canada', 'Canada'), ('Cap-Vert', 'Cap-Vert'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Chypre', 'Chypre'), ('Colombie', 'Colombie'), ('Comores', 'Comores'), ('Congo', 'Congo'), ('Costa Rica', 'Costa Rica'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Croatie', 'Croatie'), ('Cuba', 'Cuba'), ('Danemark', 'Danemark'), ('Djibouti', 'Djibouti'), ('Dominique', 'Dominique'), ('Égypte', 'Égypte'), ('El Salvador', 'El Salvador'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Équateur', 'Équateur'), ('Érythrée', 'Érythrée'), ('Espagne', 'Espagne'), ('Estonie', 'Estonie'), ('États-Unis', 'États-Unis'), ('Éthiopie', 'Éthiopie'), ('Fédération de Russie', 'Fédération de Russie'), ('Fidji', 'Fidji'), ('Finlande', 'Finlande'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Général', 'Général'), ('Géorgie', 'Géorgie'), ('Ghana', 'Ghana'), ('Grèce', 'Grèce'), ('Grenade', 'Grenade'), ('Guatemala', 'Guatemala'), ('Guinée', 'Guinée'), ('Guinée Bissau', 'Guinée Bissau'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Guyana', 'Guyana'), ('Haïti', 'Haïti'), ('Honduras', 'Honduras'), ('Hongrie', 'Hongrie'), ('Îles Marshall', 'Îles Marshall'), ('Îles Salomon', 'Îles Salomon'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ("Iran (République islamique d')", "Iran (République islamique d')"), ('Iraq', 'Iraq'), ('Irlande', 'Irlande'), ('Islande', 'Islande'), ('Israël', 'Israël'), ('Italie', 'Italie'), ('Jamaïque', 'Jamaïque'), ('Japon', 'Japon'), ('Jordanie', 'Jordanie'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kirghizistan', 'Kirghizistan'), ('Kiribati', 'Kiribati'), ('Koweït', 'Koweït'), ('Lesotho', 'Lesotho'), ('Lettonie', 'Lettonie'), ('Liban', 'Liban'), ('Libéria', 'Libéria'), ('Libyenne, jamahiriya arabe', 'Libyenne, jamahiriya arabe'), ('Liechtenstein', 'Liechtenstein'), ('Lituanie', 'Lituanie'), ('Luxembourg', 'Luxembourg'), ('Macédoine', 'Macédoine'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaisie'), ('Malawi', 'Malawi'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malte', 'Malte'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mexique', 'Mexique'), ('Micronésie (états fédérés de)', 'Micronésie (états fédérés de)'), ('Monaco', 'Monaco'), ('Mongolie', 'Mongolie'), ('Monténégro', 'Monténégro'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibie', 'Namibie'), ('Nauru', 'Nauru'), ('Népal', 'Népal'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigéria', 'Nigéria'), ('Norvège', 'Norvège'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Oman', 'Oman'), ('Ouganda', 'Ouganda'), ('Ouzbékistan', 'Ouzbékistan'), ('Pakistan', 'Pakistan'), ('Palaos', 'Palaos'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée'), ('Paraguay', 'Paraguay'), ('Pays-Bas', 'Pays-Bas'), ('Pérou', 'Pérou'), ('Philippines', 'Philippines'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('République arabe syrienne', 'République arabe syrienne'), ('République centrafricaine', 'République centrafricaine'), ('République de Corée', 'République de Corée'), ('République de Moldavie', 'République de Moldavie'), ('République démocratique du Congo', 'République démocratique du Congo'), ('République démocratique populaire lao', 'République démocratique populaire lao'), ('République dominicaine', 'République dominicaine'), ('République populaire démocratique de Corée', 'République populaire démocratique de Corée'), ('République tchèque', 'République tchèque'), ('République-unie de Tanzanie', 'République-unie de Tanzanie'), ('Roumanie', 'Roumanie'), ('Royaume-Uni', 'Royaume-Uni'), ('Rwanda', 'Rwanda'), ('Saint-Kitts-et-Nevis', 'Saint-Kitts-et-Nevis'), ('Saint-Marin', 'Saint-Marin'), ('Saint-Siège (État de la Cité du Vatican)', 'Saint-Siège (État de la Cité du Vatican)'), ('Saint-Vincent-Et-Les Grenadines', 'Saint-Vincent-Et-Les Grenadines'), ('Sainte-Lucie', 'Sainte-Lucie'), ('Samoa', 'Samoa'), ('Sans objet', 'Sans objet'), ('Sao Tomé-et-Principe', 'Sao Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Serbie', 'Serbie'), ('Serbie-Monténégro (cf. scission)', 'Serbie-Monténégro (cf. scission)'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapour'), ('Slovaquie', 'Slovaquie'), ('Slovénie', 'Slovénie'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Sri Lanka', 'Sri Lanka'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Suriname', 'Suriname'), ('Swaziland', 'Swaziland'), ('Tadjikistan', 'Tadjikistan'), ('Tchad', 'Tchad'), ('Thaïlande', 'Thaïlande'), ('Timor-Leste', 'Timor-Leste'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinité-et-Tobago', 'Trinité-et-Tobago'), ('Tunisie', 'Tunisie'), ('Turkménistan', 'Turkménistan'), ('Turquie', 'Turquie'), ('Tuvalu', 'Tuvalu'), ('Ukraine', 'Ukraine'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Venezuela', 'Venezuela'), ('Viet Nam', 'Viet Nam'), ('Yémen', 'Yémen'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')])),
                ('partenariatinter', models.TextField(help_text='Principaux partenariats internationaux *', verbose_name='Principaux partenariats internationaux *')),
                ('equipement', models.TextField(help_text='Principaux equipements, terrains, materiels *', verbose_name='Principaux equipements, terrains, materiels *')),
                ('photoLabo', models.ImageField(help_text='Joindre une photo de votre laboratoire/equipe de recherche *', verbose_name='Joindre une photo de votre laboratoire/equipe de recherche *', upload_to=annuaire.models.LaboEquip.user_directory_path)),
                ('logoLabo', models.ImageField(help_text='Joindre une photo de votre laboratoire/equipe de recherche *', verbose_name='Joindre une photo de votre laboratoire/equipe de recherche *', upload_to=annuaire.models.LaboEquip.user_directory_path2)),
                ('nom', models.CharField(help_text='Nom *', max_length=100, verbose_name='Nom *')),
                ('prenom', models.CharField(help_text='Prenom *', max_length=100, verbose_name='Prenom *')),
                ('rangUniv', models.CharField(help_text='Rang Universitaire *', max_length=100, verbose_name='Rang Universitaire *')),
                ('discipline', models.CharField(help_text='Discipline *', max_length=100, verbose_name='Discipline *')),
                ('autreFct', models.CharField(help_text='Autre Fonction *', max_length=200, verbose_name='Autre Fonction ')),
                ('phoneNumb', models.CharField(help_text='Numero de telephone direct *', max_length=200, verbose_name='Numero de telephone direct *')),
                ('afficheNumPub', models.BooleanField(help_text='Cocher pour afficher le numero publiquement', verbose_name='Cocher pour afficher le numero publiquement')),
                ('emailRsp', models.EmailField(help_text='Email direct *', max_length=100, verbose_name='Email direct *')),
                ('afficheMailPub', models.BooleanField(help_text="Cocher pour l'email publiquement", verbose_name="Cocher pour l'email publiquement")),
                ('cvResp', models.FileField(help_text='Joindre CV', verbose_name='Joindre CV', upload_to=annuaire.models.LaboEquip.user_directory_path3)),
                ('effectifs', models.FloatField(help_text="Effectifs <i>(Ne sont comptabilises que les chercheurs permanents.Ne pas comptabiliser les chercheurs visiteurs ou collaborations occasionnelles. Ecrire 0 si la categorie n'est pas concernee)</i>", verbose_name="Effectifs <i>(Ne sont comptabilises que les chercheurs permanents.Ne pas comptabiliser les chercheurs visiteurs ou collaborations occasionnelles. Ecrire 0 si la categorie n'est pas concernee)</i>")),
                ('profUniv', models.FloatField(help_text='Professeurs des universites (ou equivalent) *', verbose_name='Professeurs des universites (ou equivalent) *')),
                ('metConf', models.FloatField(help_text='Maitres de conference (ou equivalent) *', verbose_name='Maitres de conference (ou equivalent) *')),
                ('assistants', models.FloatField(help_text='Assistants (ou equivalents) *', verbose_name='Assistants (ou equivalents) *')),
                ('doctorants', models.FloatField(help_text='Doctorants *', verbose_name='Doctorants *')),
                ('autresComp', models.FloatField(help_text='Autres *', verbose_name='Autres *')),
                ('listeChercheurs', models.TextField(help_text="Liste des chercheurs de l'unite *", verbose_name="Liste des chercheurs de l'unite *")),
                ('probAxeRech', models.CharField(help_text='Problematiques et axes de recherches *', max_length=200, verbose_name='Problematiques et axes de recherches *')),
                ('mots_cles', models.CharField(help_text='Mots cles *', max_length=200, verbose_name='Mots cles *')),
                ('nombrePub', models.FloatField(help_text='Nombre de publications de rang international (5 dernires annees)*', verbose_name='Nombre de publications de rang international (5 dernires annees)*')),
                ('autrePub', models.FloatField(help_text='Autres publications dont actes de colloque (5 dernieres annees) *', verbose_name='Autres publications dont actes de colloque (5 dernieres annees) *')),
                ('theseSout', models.FloatField(help_text='Nombre de theses soutenues (5 dernieres annees) *', verbose_name='Nombre de theses soutenues (5 dernieres annees) *')),
                ('infoComple', models.TextField(help_text='Informations Complementaires', verbose_name='Informations Complementaires')),
                ('show', models.CharField(default=0, max_length=3, verbose_name='A afficher publiquement', choices=[('1', 'Visible sur le Site'), ('0', 'Invisible sur le Site')])),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsMajeur',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('auteurs', models.CharField(max_length=255, blank=True, verbose_name='auteur(s)')),
                ('titre', models.CharField(max_length=255, null=True, blank=True, verbose_name='titre')),
                ('revue', models.CharField(max_length=255, null=True, blank=True, verbose_name='revue')),
                ('annee', models.CharField(max_length=255, null=True, blank=True, verbose_name='Date de publication')),
                ('nb_pages', models.CharField(max_length=255, null=True, blank=True, verbose_name='nombre de pages')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsMajeurEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('auteurs', models.CharField(max_length=255, blank=True, verbose_name='auteur(s)')),
                ('titre', models.CharField(max_length=255, null=True, blank=True, verbose_name='titre')),
                ('revue', models.CharField(max_length=255, null=True, blank=True, verbose_name='revue')),
                ('annee', models.CharField(max_length=255, null=True, blank=True, verbose_name='Date de publication')),
                ('nb_pages', models.CharField(max_length=255, null=True, blank=True, verbose_name='nombre de pages')),
                ('chercheur', models.ForeignKey(related_name='publications', to='annuaire.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('chercheur', models.OneToOneField(serialize=False, primary_key=True, to='annuaire.Chercheur')),
                ('titre', models.CharField(max_length=255, null=True, blank=True, verbose_name='Titre')),
                ('annee', models.IntegerField(null=True, blank=True, verbose_name='Année de soutenance (réalisée ou prévue)')),
                ('directeur', models.CharField(max_length=255, null=True, blank=True, verbose_name='Directeur')),
                ('etablissement', models.CharField(max_length=255, null=True, blank=True, verbose_name='Établissement de soutenance')),
                ('nb_pages', models.IntegerField(null=True, blank=True, verbose_name='Nombre de pages')),
            ],
        ),
        migrations.AddField(
            model_name='publicationsmajeur',
            name='chercheur',
            field=models.ForeignKey(related_name='publications', to='annuaire.Chercheur'),
        ),
        migrations.AddField(
            model_name='chercheur',
            name='etablissement_autre_pays',
            field=models.ForeignKey(db_column='etablissement_autre_pays', verbose_name="pays de l'établissement", related_name='etablissement_autre_pays', to_field='code', null=True, blank=True, to='references.Pays'),
        ),
    ]
